apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/mariadb" # Thư mục này sẽ nằm trên ổ cứng server của bạn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: ejbca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "" # Để trống để nó khớp với PV thủ công bên trên
